# Generated by Django 5.1 on 2024-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=False)),
            ],
        ),
    ]
